export const SET_UNIT_TEMP = 'SET_UNIT_TEMP'
export const SET_LOCALE = 'SET_LOCALE'
export const SET_FORECAST = 'SET_FORECAST'
export const SET_LOCATION = 'SET_LOCATION'
export const SET_CURRENT = 'SET_CURRENT'
